version: 2.1

jobs:
  job:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run:
          name: Add label 'run-ci'
          command: echo 'Add label'
     

workflows:
  label-pr-workflow:
    jobs:
      - job
