version: 2.1

jobs:
  job:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run:
          name: Merge PR
          command: echo 'Merge PR'
     

workflows:
  merge-pr-workflow:
    jobs:
      - job
