version: 2.1

jobs:
  job:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run:
          name: Open PR
          command: echo "Open PR"
     

workflows:
  open-pr-workflow:
    jobs:
      - job
