# "Low code" Review agent
# Looks a pull request and issues "comprehensive" feedback
# Not as full featured as the claude code actions example since it's all inlined in the config
# Required env vars:
#  - ANTHROPIC_API_KEY (for claude)
#  - GH_TOKEN (for CLI)
# Areas to improve:
#  - Specialized prompts instead of generic review
#  - GitLab/BitBucket support
#  - Not using inline PR comments super effectively.
version: 2.1

jobs:
  review-agent:
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - run:
          name: Configure MCP servers
          command: |
            cat > /tmp/review_mcp_config.json  \<< EOF
            {
              "mcpServers": {
                "github": {
                  "command": "npx",
                  "args": [
                    "-y",
                    "@modelcontextprotocol/server-github"
                  ],
                  "env": {
                    "GITHUB_PERSONAL_ACCESS_TOKEN": "${GH_TOKEN}",
                    "GITHUB_HOST": "${GITHUB_HOST}",
                    "GITHUB_REPOSITORY": "<<pipeline.event.github.repository.owner.login>>/<<pipeline.event.github.repository.name>>",
                    "GITHUB_PR_NUMBER": "<<pipeline.event.github.pull_request.number>>"
                  }
                }
                }
              }
            EOF
      - run:
          name: Install gh cli
          command: |
            sudo apt update
            sudo apt install -y gh
      - run:
          name: Install Claude Code
          command: |
            npm install -g @anthropic-ai/claude-code
      - run: 
          name: Debug - List available tools
          command: |
            claude --mcp-config /tmp/review_mcp_config.json \
            --allowed-tools "*" \
            -p "List all available MCP tools you can see"
      - run: 
          name: Run Agent
          command: |
            claude --mcp-config /tmp/review_mcp_config.json \
            # --allowed-tools "mcp__github__get_pull_request,mcp__github__get_pull_request_files,mcp__github__create_pull_request_review,mcp__github__add_issue_comment" \
            --allowed-tools "mcp__github__get_pull_request,mcp__github__get_pull_request_files,Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh api:*)" \

            --output-format json \
            -p "$(cat .circleci/pr-review-prompt.txt)"
workflows:
  review-agent:
    jobs:
      - review-agent:
          context:
            - review-agent
