# "Low code" Review agent
# Looks a pull request and issues "comprehensive" feedback
# Not as full featured as the claude code actions example since it's all inlined in the config
# Required env vars:
#  - ANTHROPIC_API_KEY (for claude)
#  - GH_TOKEN (for CLI)
# Areas to improve:
#  - Specialized prompts instead of generic review
#  - GitLab/BitBucket support
#  - Not using inline PR comments super effectively.
version: 2.1

jobs:
  review-agent:
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - run:
          name: Configure MCP servers
          command: |
            cat > /tmp/review_mcp_config.json  \<< EOF
            {
              "mcpServers": {
                "github": {
                  "command": "docker",
                  "args": [
                    "run",
                    "-i",
                    "--rm",
                    "-e",
                    "GITHUB_PERSONAL_ACCESS_TOKEN",
                    "-e",
                    "GITHUB_HOST",
                    "-e",
                    "GITHUB_REPOSITORY",
                    "-e",
                    "GITHUB_PR_NUMBER",
                    "ghcr.io/github/github-mcp-server:latest"
                  ],
                  "env": {
                    "GITHUB_PERSONAL_ACCESS_TOKEN": "${GH_TOKEN}",
                    "GITHUB_HOST": "${GITHUB_HOST}",
                    "GITHUB_REPOSITORY": "<<pipeline.event.github.repository.owner.login>>/<<pipeline.event.github.repository.name>>",
                    "GITHUB_PR_NUMBER": "<<pipeline.event.github.pull_request.number>>"
                  }
                }
                }
              }
            EOF
      - run:
          name: Install gh cli
          command: |
            sudo apt update
            sudo apt install -y gh
      - run:
          name: Install Claude Code
          command: |
            npm install -g @anthropic-ai/claude-code
      - run: 
          name: Run Agent
          command: |
            claude --mcp-config /tmp/review_mcp_config.json \
            --allowed-tools "mcp__github_get_pull_request__get_pull_request,mcp__github_get_pull_request_diff__get_pull_request_diff,mcp__github_inline_comment__create_inline_comment,mcp__github_create_issue_comment__create_issue_comment" \
            --output-format json \
            -p "$(cat .circleci/pr-review-prompt.txt)"
workflows:
  review-agent:
    jobs:
      - review-agent:
          context:
            - review-agent
